name: Deploy Backend

on:
  push:
    branches: [ master ]
    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to Digital Ocean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          cd ~/Final-Year-Project/Backend
          git pull
          npm install
          pm2 restart all
        EOF
