name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Ensure this matches the version you're using

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        # If you are using a package-lock.json or need to cache modules, consider adding caching steps here
    - name: Install dependencies
      run: |
        cd Backend
        npm install
    - name: Lint and Build
      run: |
        cd Backend
        npm run lint
        npm run build
